package com.gridyn.potspot;

import java.util.Arrays;
import java.util.List;

public interface Constant {
    int BLUR_RADIUS = 40;

    String FONT_ROBOTO_REGULAR = "fonts/Roboto-Regular.ttf";
    String FONT_ROBOTO_MEDIUM = "fonts/Roboto-Medium.ttf";
    String FONT_ROBOTO_LIGHT = "fonts/Roboto-Light.ttf";
    String BASE_URL = "http://potspot.podkolpakom.net/API/";
    String URL_IMAGE = "http://potspot.podkolpakom.net/imgs/";
    String BASE_IMAGE = "https://vk.com/images/camera_200.png";
    String BASE_IMAGE_OF_SPOT = "1471540131_bf57bd9810a85c7e1f94d0ea94168c19.jpg";
    String URL_BASE64 = "data:image/jpeg;base64,";
    String CONNECTION_ERROR = "Connection error";
    String SP = "settings";
    String SP_IS_LOGIN = "isLogin";
    int CAMERA = 0;
    int GALLERY = 1;
    String LOG = "log";
    long UPDATE_LOCATION_SECONDS = 10000;
    float UPDATE_LOCATION_DISTANCE = 10;
    String NOT_SPECIFIED = "Not Specified";
    String APP_PREFERENCES = "settings";
    String AP_EMAIL = "email";
    String AP_PASSWORD = "password";
    String AP_LOG_IN = "log_out";
    String MESSAGE_ACTION = "com.gridyn.potspot.NEW_MESSAGE";
    int EDIT_TIME_CODE = 1;
    String ARG_POTSPOT_AVAILABLE = "availArr";
    String HOME_ONE_TIME = "homeOneTime";
    String SPOT_ONE_TIME = "spotOneTime";
    String PROFILE_ONE_TIME = "profOneTime";
    String ADD_SPOT_ONE_TIME = "addSpotOneTime";
    //    String STRIPE_KEY = "sk_test_volRoAtAFfrYZEKLPVOTQh68";
    String STRIPE_KEY = "pk_test_Pb367hjLuJ7NikNs8hxaatHl";
    String SPOT_NAME = "spotname";
    String NOTIF_TEXT = "notiftext";
    String SPOT_ID = "spotid";
    String OPEN_FOR_BOOK = "forBook";
    String DATE_TIME_REQUEST = "datetime";
    String REQUEST_ID = "reqId";
    String PAYMENT_SUCCESSFULL = "paymentsuccessfull";
    String PROGRESS_MESSAGE = "progress";
    String PARTY_SIZE = "partySize";
    String ARG_SPOT_ID = "potspotid";
    String ARG_WHO_INVITE = "whoinvitename";
    String ARG_WHO_INVITE_ID = "whoinviteid";
    String INTENT_INVITE_FRIEND = "invite";
    String SUCCESS = "success";
    String USER_ID = "userId";
    String SPOT_PRICE = "spotPrice";
    String USER_NAME = "username" ;
    public static List<String> FBpermissionNeeds = Arrays.asList("email", "public_profile");
    String FB_APP_LOGIN = "fblogin";
    String GPLUS_APP_LOGIN = "gpluslogin";
    String FB_ID = "fbid";
    String FB_TOKEN = "fbtoken";
    String GPLUS_TOKEN = "gplus";
    String ACCEPT_REQ_MODEL = "reqmodel";
    String BOOK_TIME = "time";
}
